CREATE TABLE SMG_User(
	SUS_USERID serial primary key,
	SUS_EMAIL varchar(100) not null,
	SUS_PASSWORD varchar(100) not null,
    SUS_DATECREA timestamp default LOCALTIMESTAMP,
    SUS_DATEMODIF timestamp
);

CREATE TABLE SMG_Director(
	SDI_DIRECTORID serial primary key,
	SDI_FIRSTNAME varchar(30) not null,
	SDI_LASTNAME varchar(30) not null,
    SDI_DATECREA timestamp default LOCALTIMESTAMP,
    SDI_DATEMODIF timestamp
);

CREATE TABLE SMG_Movie(
	SMO_MOVIEID serial primary key,
	SMO_TITLE varchar(500) not null,
	SMO_DURATION INTERVAL not null,
	SMO_RELEASEYEAR int not null,
    SMO_DIRECTORID serial,
    SMO_DATECREA timestamp default LOCALTIMESTAMP,
    SMO_DATEMODIF timestamp,
    FOREIGN KEY(SMO_DIRECTORID) REFERENCES SMG_Director(SDI_DIRECTORID) ON DELETE CASCADE
);

CREATE TABLE SMG_Actor(
	SAC_ACTORID serial primary key,
	SAC_FIRSTNAME varchar(30) not null,
	SAC_LASTNAME varchar(30) not null,
	SAC_BIRTHDATE DATE not null,
    SAC_DATECREA timestamp default LOCALTIMESTAMP,
    SAC_DATEMODIF timestamp
);

CREATE TABLE SMG_Favorite(
	SFA_MOVIEID serial,
	SFA_USERID serial,
    SFA_DATECREA timestamp default LOCALTIMESTAMP,
    SFA_DATEMODIF timestamp,
	PRIMARY KEY(SFA_MOVIEID,SFA_USERID),
	FOREIGN KEY(SFA_USERID) REFERENCES SMG_User(SUS_USERID) ON DELETE CASCADE,
	FOREIGN KEY(SFA_MOVIEID) REFERENCES SMG_Movie(SMO_MOVIEID) ON DELETE CASCADE
);

CREATE TABLE SMG_Perform(
	SPE_MOVIEID serial,
	SPE_ACTORID serial,
	SPE_ROLE varchar(100),
	SPE_ISLEADROLE bool,
    SPE_DATECREA timestamp default LOCALTIMESTAMP,
    SPE_DATEMODIF timestamp,
	PRIMARY KEY(SPE_MOVIEID,SPE_ACTORID),
	FOREIGN KEY(SPE_ACTORID) REFERENCES SMG_Actor(SAC_ACTORID) ON DELETE CASCADE,
	FOREIGN KEY(SPE_MOVIEID) REFERENCES SMG_Movie(SMO_MOVIEID) ON DELETE CASCADE
);
