CREATE TABLE "SMG_User"(
	SUS_USERID serial primary key,
	SUS_EMAIL varchar(100) not null,
	"SUS_PASSWORD" varchar(30) not null,
    SUS_DATECREA date default CURRENT_DATE,
    SUS_DATEMODIF date
);

CREATE TABLE SMG_Movie(
	SMO_MOVIEID serial primary key,
	SMO_TITLE varchar(100) not null,
	SMO_DURATION INTERVAL not null,
	SMO_RELEASEYEAR int not null,
    SMO_DATECREA date,
    SMO_DATEMODIF date
);

CREATE TABLE SMG_Actor(
	SAC_ACTORID serial primary key,
	SAC_FIRSTNAME varchar(30) not null,
	SAC_LASTNAME varchar(30) not null,
	SAC_BIRTHDATE DATE not null,
    SAC_DATECREA date default CURRENT_DATE,
    SAC_DATEMODIF date
);

CREATE TABLE SMG_Director(
	SDI_DIRECTORID serial primary key,
	SDI_FIRSTNAME varchar(30) not null,
	SDI_LASTNAME varchar(30) not null,
    SDI_DATECREA date default CURRENT_DATE,
    SDI_DATEMODIF date
);

CREATE TABLE SMG_Favorite(
	SFA_MOVIEID serial,
	SFA_USERID serial,
    SFA_DATECREA date default CURRENT_DATE,
    SFA_DATEMODIF date,
	PRIMARY KEY(SFA_MOVIEID,SFA_USERID),
	FOREIGN KEY(SUS_USERID) REFERENCES "SMG_User"(SUS_USERID),
	FOREIGN KEY(MOVIEID) REFERENCES SMG_Movie(SMO_MOVIEID)
);

CREATE TABLE SMG_Perform(
	SPE_MOVIEID serial,
	SPE_ACTORID serial,
	"SPE_ROLE" varchar(30),
	SPE_ISLEADROLE bool,
    SPE_DATECREA date default CURRENT_DATE,
    SPE_DATEMODIF date,
	PRIMARY KEY(SPE_MOVIEID,SPE_ACTORID),
	FOREIGN KEY(SPE_ACTORID) REFERENCES SMG_Actor(SAC_ACTORID),
	FOREIGN KEY(SPE_MOVIEID) REFERENCES SMG_Movie(SMO_MOVIEID)
);